
(import (scheme base))
(import (scheme write))
(import (bencoding))

(define data '(#(("given name" . "Atsushi")
                 ("family name" . "Saito")
                 ("weight" . 46)
                 ("height" . 164))
               #(("given name" . "Mikoto")
                 ("family name" . "Misaka")
                 ("weight" . 45)
                 ("height" . 161))
               #(("given name" . "Armin")
                 ("family name" . "Arlert")
                 ("weight" . 55)
                 ("height" . 163))))

(let* ((encoded (bencoding-construct-bytevector data))
       (decoded (bencoding-parse-bytevector encoded)))
  (write encoded)
  (newline)
  (write decoded)
  (newline))
